after-login-command = []
after-startup-command = ['layout v_accordion']
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 24
#default-root-container-layout = 'tiles'
#default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       6
outer.bottom =     6
outer.top =        6
outer.right =      6

[workspace-to-monitor-force-assignment]
1 = 'main'
10 = 'secondary'
#t = 'main'

[mode.main.binding]
# cmd-alt-ctrl-shift is mapped in UHK and superkey
cmd-alt-ctrl-shift-z = 'focus up'
cmd-alt-ctrl-shift-x = 'focus down'
cmd-alt-ctrl-shift-left = 'focus left'
cmd-alt-ctrl-shift-right = 'focus right'
cmd-alt-ctrl-shift-up = 'focus up'
cmd-alt-ctrl-shift-down = 'focus down'
cmd-alt-ctrl-shift-t = 'exec-and-forget ~/.config/aerospace/focus_window.sh com.github.wez.wezterm WezTerm'
cmd-alt-ctrl-shift-c = 'move-node-to-monitor --wrap-around --focus-follows-window next'
cmd-alt-ctrl-shift-tab = 'focus-monitor --wrap-around next'
cmd-alt-ctrl-shift-minus = 'resize smart -50'
cmd-alt-ctrl-shift-equal = 'resize smart +50'
